/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ad_proyecto.Vista;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;

/**
 *
 * @author Antonio
 */
public class ElegirBBDD extends javax.swing.JFrame {

    private ButtonGroup butgro = null;
    
    /**
     * Creates new form ElegirBBDD
     */
    public ElegirBBDD() {
        initComponents();
        
        // Grupo de opciones.
        butgro = new ButtonGroup();
        butgro.add(rbMariaDB);
        butgro.add(rbObjectDB);
        butgro.add(rbMongoDB);
        
        rbMariaDB.setSelected(true);
    }
    
    public int getOpcion() {
        int ret;
        
        // MariaDB
        if (rbMariaDB.isSelected())
            ret = 1;
        // ObjectDB
        else if (rbObjectDB.isSelected())
            ret = 2;
        // MongoDB
        else
            ret = 3;
        
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlElegirBBDD = new javax.swing.JPanel();
        lblBBDDMsg = new javax.swing.JLabel();
        pnlElegir = new javax.swing.JPanel();
        rbMariaDB = new javax.swing.JRadioButton();
        rbObjectDB = new javax.swing.JRadioButton();
        rbMongoDB = new javax.swing.JRadioButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBBDDMsg.setText("Elige el tipo de BBDD que desees usar");

        rbMariaDB.setText("MariaDB");

        rbObjectDB.setText("ObjectDB");

        rbMongoDB.setText("MongoDB");

        javax.swing.GroupLayout pnlElegirLayout = new javax.swing.GroupLayout(pnlElegir);
        pnlElegir.setLayout(pnlElegirLayout);
        pnlElegirLayout.setHorizontalGroup(
            pnlElegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElegirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlElegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMariaDB)
                    .addComponent(rbObjectDB)
                    .addComponent(rbMongoDB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlElegirLayout.setVerticalGroup(
            pnlElegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElegirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMariaDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbObjectDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbMongoDB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout pnlElegirBBDDLayout = new javax.swing.GroupLayout(pnlElegirBBDD);
        pnlElegirBBDD.setLayout(pnlElegirBBDDLayout);
        pnlElegirBBDDLayout.setHorizontalGroup(
            pnlElegirBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElegirBBDDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlElegirBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlElegirBBDDLayout.createSequentialGroup()
                        .addComponent(pnlElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlElegirBBDDLayout.createSequentialGroup()
                        .addGroup(pnlElegirBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlElegirBBDDLayout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar))
                            .addGroup(pnlElegirBBDDLayout.createSequentialGroup()
                                .addComponent(lblBBDDMsg)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        pnlElegirBBDDLayout.setVerticalGroup(
            pnlElegirBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElegirBBDDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBBDDMsg)
                .addGap(18, 18, 18)
                .addComponent(pnlElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlElegirBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlElegirBBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlElegirBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirBBDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JLabel lblBBDDMsg;
    public javax.swing.JPanel pnlElegir;
    public javax.swing.JPanel pnlElegirBBDD;
    public javax.swing.JRadioButton rbMariaDB;
    public javax.swing.JRadioButton rbMongoDB;
    public javax.swing.JRadioButton rbObjectDB;
    // End of variables declaration//GEN-END:variables
}
